theme = "molokai-override"
[editor]
true-color              = true
rulers                  = [80, 100]
end-of-line-diagnostics = "hint"
auto-format             = false
cursorline              = true
color-modes             = true
[editor.cursor-shape]
normal = "bar"
insert = "bar"
select = "bar"
[editor.inline-diagnostics]
cursor-line = "error"
[editor.lsp]
display-inlay-hints = true
[editor.whitespace.render]
tab     = "all"
nbsp    = "all"
nnbsp   = "all"
newline = "all"
[editor.whitespace.characters]
newline = "$"
[editor.indent-guides]
render    = true
character = "|"
[editor.file-picker]
hidden  = false
parents = false
[keys.normal]
i = ["insert_mode", "collapse_selection"]
a = ["insert_mode", "collapse_selection"]
u = ["undo", "collapse_selection"]
U = ["redo", "collapse_selection"]
p = ["paste_after", "collapse_selection"]
P = ["paste_before", "collapse_selection"]
#d.d = [
#	"extend_to_line_bounds",
#	"yank_main_selection_to_clipboard",
#	"delete_selection",
#]
#x = ["delete_selection"]
#y.y = [
#	"extend_to_line_bounds",
#	"yank_main_selection_to_clipboard",
#	"normal_mode",
#	"collapse_selection",
#]
F12 = [":set line-number relative"]
[keys.insert]
esc = ["collapse_selection", "normal_mode"]
